services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  Psr\Log\LoggerInterface: '@App\Infrastructure\Log\Logger'
  App\Common\Output\OutputInterface: '@App\Infrastructure\Output\OutputService'

  App\:
    resource: '../src/*'
    exclude:
      - '../src/*/ValueObject/*'
